### PR TITLE
Update Badge.pm

### PR DESCRIPTION
**Pull request by mishin**
Hi, Fayland
I add 3 badges

'github_tag' will be working ok,
but 'license' and 'version' need  cpan distribution name
but usually $repository_name is not equal to cpan distribution name
so I want just  distribution name, how I can get it?
or parse from git, any ideas?
thanks

### CODE REVIEW

**Comment by mishin** [comment]
Hi, Fayland,
I add
 $cpan_dist_name=$distmeta->{name};
it must works!

**Comment by fayland** [comment]
I think that's dist_name I provided.

https://github.com/fayland/perl-Dist-Zilla-Plugin-GitHubREADME-Badge/blob/master/lib/Dist/Zilla/Plugin/GitHubREADME/Badge.pm#L27

can you verify?

Thanks

**Comment by mishin** [comment]
Fayland , yes, it's more strait way, thanks

**Comment by mishin** [comment]
Well, I correct according your changes

**Pull request merged**
